name: Deploy Toolkit

on:
  push:
    branches:
      - main
    paths:
      - 'ice-cream-dataops/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: cognite/toolkit:0.6.53
    environment: ${{ github.event.inputs.environment || 'test' }}
    strategy:
      matrix:
        environment:
          - ${{ github.event.inputs.environment || 'test' }}
    env:
      LOGIN_FLOW: client_credentials
      CDF_CLUSTER: westeurope-1
      CDF_PROJECT: cdf-bootcamp-50-${{ matrix.environment }}
      IDP_TENANT_ID: 16e3985b-ebe8-4e24-9da4-933e21a9fc81
      IDP_TOKEN_URL: https://login.microsoftonline.com/16e3985b-ebe8-4e24-9da4-933e21a9fc81/oauth2/v2.0/token
      IDP_CLIENT_ID: ${{ vars.IDP_CLIENT_ID }}
      IDP_CLIENT_SECRET: ${{ secrets.IDP_CLIENT_SECRET }}
      DATA_DEVELOPER_SOURCE_ID: ${{ vars.DATA_DEVELOPER_SOURCE_ID }}
      DATA_PIPELINE_OEE_CLIENT_ID: ${{ vars.DATA_PIPELINE_OEE_CLIENT_ID }}
      DATA_PIPELINE_OEE_CLIENT_SECRET: ${{ secrets.DATA_PIPELINE_OEE_CLIENT_SECRET }}
      DATA_PIPELINE_OEE_SOURCE_ID: ${{ vars.DATA_PIPELINE_OEE_SOURCE_ID }}
      ICAPI_EXTRACTORS_CLIENT_ID: ${{ vars.ICAPI_EXTRACTORS_CLIENT_ID }}
      ICAPI_EXTRACTORS_CLIENT_SECRET: ${{ secrets.ICAPI_EXTRACTORS_CLIENT_SECRET }}
      ICAPI_EXTRACTORS_SOURCE_ID: ${{ vars.ICAPI_EXTRACTORS_SOURCE_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify auth
        run: yes | cdf auth verify
      - name: Build
        run: cdf build --env=${{ matrix.environment }}
      - name: Deploy
        run: cdf deploy --env=${{ matrix.environment }}